@host = http://localhost:8080
@memberId = 2

### Member 생성
POST {{host}}/api/v1/members
Content-Type: application/json

{
  "email": "ccc@todo.com",
  "name": "bbbb"
}

### Member 조회
GET {{host}}/api/v1/members/{{memberId}}
Accept: application/json


### Member 생성 (비속어에 의한 예외발생)
POST {{host}}/api/v1/members
Content-Type: application/json

{
  "email": "ccc@todo.com",
  "name": "fuck"
}
