@host = http://localhost:8080
@memberId = 1

### Member 생성
POST {{host}}/api/v1/members
Content-Type: application/json

{
  "email": "a@todo.com",
  "name": "Alice"
}

### Member 조회
GET {{host}}/api/v1/members/{{memberId}}
Accept: application/json
