server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: todo
    password: todo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    org.hibernate.SQL: debug
